# Site settings
title: StopPesten
baseurl: "StopPesten"
url: "https://stenoverdijk.github.io" # the base hostname & protocol for your site, e.g. http://example.com
timezone: "Europe/Amsterdam"
email: your-email@example.com

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/sass

# Plugins
plugins:
  - jekyll-feed

# Social
github_username:  jekyll
twitter_username: jekyllrb
