# Site settings
title: StopPesten
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
timezone: "Europe/Amsterdam"
email: your-email@example.com

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/sass

# Exclude
exclude:
  - CNAME

# Plugins
plugins:
  - jekyll-feed

# Social
github_username:  jekyll
twitter_username: jekyllrb
